---
- hosts: servers
  become: true
  become_user: root

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python2.7-dev
        # - python3.5-dev
        - python-virtualenv
        - python-pip
        - nfs-common
        - ceph-common
    - name: update pip
      pip:
        name: pip
        state: latest
    - name: install py dependencies
      pip:
        name: python-openstackclient
        state: present
